name: dsmr-db
services:
  app:
    image: postgres:14-alpine
    restart: unless-stopped  
    network_mode: dsmr_default
    container_name: Dsmrdb1
    volumes:
      - type: bind
        source: /DATA/AppData/DSMR/data/dsmrdb
        target: /var/lib/postgresql/data
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
    hostname: DSMR-Database
networks:
  dsmr_default:
    name: dsmr_default
    driver: bridge       
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: DSMR-Reader Database
  tagline:
    en_us: DSMR-Reader Database
  developer: ''
  author: ''
  icon: https://avatars.githubusercontent.com/u/57727360?s=48&v=4
  thumbnail: https://github.com/dsmrreader/dsmr-reader/blob/v5/docs/_static/screenshots/v5/frontend/dashboard.png?raw=true
  title:
    en_us: Dsmr-reader Database
  category: Fastxlstore
