name: music-assistant
services:
  app:
    image: ghcr.io/music-assistant/server:latest
    restart: unless-stopped
    ports:
      - target: 8095
        published: 8095
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Music-Assistant
        target: /data
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Music Assistant
  tagline:
    en_us: Music Assistant
  developer: ''
  author: ''
  hostname: Music-Assistant
  icon: https://avatars.githubusercontent.com/u/71128003?s=200&v=4
  thumbnail: https://music-assistant.io/assets/screenshots/screen1.png
  title:
    en_us: Music Assistant
  category: Fastxlstore
  port_map: '8095'