name: realdebrid-client
services:
  app:
    image: rogerfar/rdtclient:latest
    restart: unless-stopped
    ports:
      - target: 6500
        published: 6500
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Realdebrid client
  tagline:
    en_us: Realdebrid client
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/caddy.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/caddy.png
  title:
    en_us: Realdebrid client
  category: Fastxlstore
  port_map: '80'
