name: dsmr-reader
services:
  app:
    image: ghcr.io/xirixiz/dsmr-reader-docker:latest
    restart: unless-stopped
    hostname: DSMR-Reader
    network_mode: dsmr-db_default    
    ports:
      - target: 80
        published: 7777
        protocol: tcp   
    volumes:
      - type: bind
        source: /DATA/AppData/DSMR/data/backups
        target: /app/backups
    links:
      - dsmr-db          
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: DSMR-Reader For p1 reader
  tagline:
    en_us: Dsmr
  developer: ''
  author: ''
  icon: https://avatars.githubusercontent.com/u/57727360?s=48&v=4
  thumbnail: https://github.com/dsmrreader/dsmr-reader/blob/v5/docs/_static/screenshots/v5/frontend/dashboard.png?raw=true
  title:
    en_us: Dsmr-reader
  category: Fastxlstore
  port_map: '7777'
