name: DSMR
services:
  app:
    image: ghcr.io/xirixiz/dsmr-reader-docker:latest
    restart: unless-stopped
    ports:
      - target: 7777
        published: 80
        protocol: tcp
      - target: 7779
        published: 443
        protocol: tcp        
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data/backups
        target: /app/backups
    environment:
      - TZ=Europe/Amsterdam
      - DJANGO_TIME_ZONE=Europe/Amsterdam
      - VIRTUAL_HOST=localhost      
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: DSMR
  tagline:
    en_us: DSMR
  developer: ''
  author: 
  icon: ''
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/caddy.png
  title:
    en_us: DSMR
  category: Fastxlstore
  port_map: '7777'
